name: Deploy React App to S3 + CloudFront

on:
  push:
    tags: 
      - "[0-9]+.[0-9]+.[0-9]+-[dp].[0-9]+"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Extract Environment from Tag
      id: extract_env
      run: |
        TAG_NAME="${GITHUB_REF##*/}"
        if [[ "$TAG_NAME" == *-d* ]]; then
          echo "env=DEV" >> $GITHUB_OUTPUT
        elif [[ "$TAG_NAME" == *-p* ]]; then
          echo "env=PROD" >> $GITHUB_OUTPUT
        else
          echo "Unknown environment from tag: $TAG_NAME"
          exit 1
        fi

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'      

    - name: Install dependencies
      run: npm install --legacy-peer-deps

    - name: Create .env.production
      run: |
        cat > .env.production << EOF
        REACT_APP_NODE_ENV=${{steps.extract_env.outputs.env}}
        REACT_APP_GA_KEY = ${{ secrets.GA_KEY }}
        REACT_APP_JS_KAKAO_KEY=${{ secrets.JS_KAKAO_KEY }}
        REACT_APP_REDIRECT_URI=${{ secrets[format('{0}_REDIRECT_URI', steps.extract_env.outputs.env)] }}
        REACT_APP_API_BASE=${{ secrets[format('{0}_API_BASE', steps.extract_env.outputs.env)] }}
        EOF
      # 안전: 출력 로그에 비밀값이 노출되지 않도록 shell heredoc 사용  

    - name: Build React App
      env:
        CI: false
        NODE_OPTIONS: --max_old_space_size=4096
      run: npm run build
        
    - name: Sync S3 Bucket
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete --exclude "images/*"
      env:
        AWS_S3_BUCKET: ${{ secrets[format('{0}_AWS_S3_BUCKET', steps.extract_env.outputs.env)] }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ap-northeast-2
        SOURCE_DIR: build

    - name: Invalidate CloudFront Cache
      uses: chetan/invalidate-cloudfront-action@v2
      env:
        AWS_REGION: ap-northeast-2
        DISTRIBUTION: ${{ secrets[format('{0}_CLOUDFRONT_DISTRIBUTION_ID', steps.extract_env.outputs.env)] }}
        PATHS: '/*'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
